using HierarchiaKlasPojazdow.Enumy;
using HierarchiaKlasPojazdow.Pojazdy;

Samochod samochod = new Samochod(RodzajSilnika.LPG, 125);
samochod.ZwiekszPredkosc();
samochod.ZmniejszPredkosc();
samochod.ZmniejszPredkosc();
samochod.Stop();
samochod.Start();
samochod.TestowoPrzypiszSrodowisko(Srodowisko.Wodne);
samochod.ZwiekszPredkosc();
samochod.ZwiekszPredkosc();
samochod.ZwiekszPredkosc();
samochod.ZwiekszPredkosc();
samochod.ZwiekszPredkosc();
samochod.ZwiekszPredkosc();
samochod.ZwiekszPredkosc();
samochod.ZwiekszPredkosc();
samochod.ZmniejszPredkosc();
samochod.ZmniejszPredkosc();
samochod.ZmniejszPredkosc();
samochod.ZmniejszPredkosc();
samochod.ZmniejszPredkosc();
samochod.ZmniejszPredkosc();
samochod.ZmniejszPredkosc();
samochod.ZmniejszPredkosc();
samochod.ZmniejszPredkosc();
samochod.Start();
Console.WriteLine(samochod.ToString());